# Generated by Django 4.1.1 on 2022-11-20 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_alter_educationaldocument_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationaldocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educational_document",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
