# Generated by Django 4.1.1 on 2022-10-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_citizenship_education_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citizenship",
            options={
                "ordering": ["name"],
                "verbose_name": "Страна гражданства",
                "verbose_name_plural": "Справочник - страны гражданства",
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["name"],
                "verbose_name": "Уровень образования",
                "verbose_name_plural": "Уровни образования",
            },
        ),
    ]
