version: '3'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    ports:
      - "5432:5432"
    env_file:
      - ./src/.env

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    entrypoint: /app/docker/backend/entrypoint.sh
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - ./src/.env

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my-network: