# Generated by Django 4.1.1 on 2022-12-03 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postgraduates", "0005_alter_explanatorynote_postgraduate"),
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "новый"), (5, "одобрен")], default=1
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план заголовок",
                "verbose_name_plural": "Учебные планы - заголовки",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("year_of_study", models.SmallIntegerField()),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип учебного плана аспиранта",
                "verbose_name_plural": "1.Справочник учебных планов - Типы учебных планов аспиранта",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlanWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "study_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_plan_works",
                        to="study_plans.studyplan",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudyWorkScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_plan_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_work_scopes",
                        to="study_plans.studyplanwork",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_genplan_visible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Наименование работы",
                "verbose_name_plural": "2.Справочник учебных планов - Наименования работ учебного плана",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="WorkScopeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("is_title_visible", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_scope_types",
                        to="study_plans.worktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объем работы",
                "verbose_name_plural": "3.Справочник учебных планов - Наименование объемов работ",
                "ordering": ["id", "sort", "title"],
            },
        ),
        migrations.CreateModel(
            name="StudyWorkScopeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=250, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "reporting_form",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "completion_mark",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("faculty_conclustion", models.TextField(blank=True, null=True)),
                (
                    "study_work_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_work_scope_details",
                        to="study_plans.studyworkscope",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_work_subjects",
                        to="faculties.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="studyworkscope",
            name="work_scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="study_plans.workscopetype",
            ),
        ),
        migrations.AddField(
            model_name="studyplanwork",
            name="work_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="study_plans.worktype"
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="plan_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="study_plans.studyplantype",
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="postgraduate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="study_plans",
                to="postgraduates.postgraduate",
            ),
        ),
    ]
