# Generated by Django 4.1.1 on 2022-10-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postgraduates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_of_study", models.SmallIntegerField()),
                (
                    "postgraduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postgraduates.postgraduate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план заголовок",
                "verbose_name_plural": "Учебные планы - заголовки",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudyWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_section_title", models.BooleanField(default=False)),
                (
                    "study_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="study_plans.studyplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("visible", models.BooleanField(default=True)),
                ("genplan_visible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Наименование работы",
                "verbose_name_plural": "Справочник наименования работ",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="WorkScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study_plans.work",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объем работы",
                "verbose_name_plural": "Справочник объемов работ",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="StudyWorkDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_table",
                    models.SmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "postgraduates.exam"),
                            (2, "faculties.subject"),
                        ],
                        default=0,
                    ),
                ),
                ("reference_key", models.IntegerField(blank=True, null=True)),
                ("deadline", models.DateField()),
                (
                    "reporting_form",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "completion_mark",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("faculty_conclustion", models.TextField(blank=True, null=True)),
                (
                    "study_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="study_plans.studywork",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studywork",
            name="work_scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="study_plans.workscope"
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="study_plans.work"
            ),
        ),
    ]
