# Generated by Django 4.1.1 on 2022-11-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study_plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип учебного плана аспиранта",
                "verbose_name_plural": "1.Справочник учебных планов - Типы учебных планов аспиранта",
                "ordering": ["sort"],
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["title"],
                "verbose_name": "Наименование работы",
                "verbose_name_plural": "2.Справочник учебных планов - Наименования работ учебного плана",
            },
        ),
        migrations.AlterModelOptions(
            name="workscope",
            options={
                "ordering": ["title"],
                "verbose_name": "Объем работы",
                "verbose_name_plural": "3.Справочник учебных планов - Наименование объемов работ",
            },
        ),
        migrations.AddField(
            model_name="studyplan",
            name="plan_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="study_plans.studyplantype",
            ),
        ),
    ]
