# Generated by Django 4.1.1 on 2022-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0002_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
