# Generated by Django 4.1.1 on 2022-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=250)),
                ("value", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Параметр приложения",
                "verbose_name_plural": "Параметры приложения",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("url_name", models.CharField(max_length=250)),
                ("sort", models.SmallIntegerField()),
                (
                    "seen_by",
                    models.IntegerField(
                        choices=[
                            (1, "аспирант"),
                            (2, "руководитель"),
                            (3, "администрация"),
                        ],
                        default=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["sort"],
            },
        ),
    ]
