# Generated by Django 4.1.1 on 2022-12-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitems",
            options={
                "ordering": ["seen_by", "sort"],
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
