# Generated by Django 4.1.1 on 2022-10-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Postgraduate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_of_study",
                    models.CharField(
                        choices=[
                            ("NA", "Не выбрано"),
                            ("FT", "Очное"),
                            ("DL", "Заочное"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                ("number_of_years", models.SmallIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("real_end_date", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="faculties.department",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="faculties.specialty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="faculties.supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аспирант",
                "verbose_name_plural": "Аспиранты",
                "ordering": ["student_id"],
            },
        ),
        migrations.CreateModel(
            name="ExplanatoryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topicality", models.TextField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                ("scientific_value", models.TextField(blank=True, null=True)),
                ("expected_result", models.TextField(blank=True, null=True)),
                ("application_area", models.TextField(blank=True, null=True)),
                ("is_topic_approved", models.BooleanField(default=False)),
                ("is_purpose_approved", models.BooleanField(default=False)),
                ("is_value_approved", models.BooleanField(default=False)),
                ("is_application_approved", models.BooleanField(default=False)),
                (
                    "postraduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postgraduates.postgraduate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("is_candidate_exam", models.BooleanField(default=False)),
                (
                    "mark",
                    models.IntegerField(
                        choices=[
                            (-1, "не выставлено"),
                            (0, "зачет"),
                            (2, "неудовлетворительно"),
                            (3, "удовлетворительно"),
                            (4, "хорошо"),
                            (5, "отлично"),
                        ],
                        default=-1,
                    ),
                ),
                (
                    "postgraduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postgraduates.postgraduate",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="faculties.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экзамен",
                "verbose_name_plural": "Экзамены",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="DissertationTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("protocol_number", models.CharField(max_length=50)),
                (
                    "postgraduate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postgraduates.postgraduate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема диссертации",
                "verbose_name_plural": "Темы диссертации",
                "ordering": ["name"],
            },
        ),
    ]
