# Generated by Django 4.1.1 on 2022-12-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dissertationtopic",
            options={
                "ordering": ["id"],
                "verbose_name": "Тема диссертации",
                "verbose_name_plural": "2.Темы диссертации",
            },
        ),
        migrations.AlterModelOptions(
            name="explanatorynotesectiontype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Раздел объяснительной записки",
                "verbose_name_plural": "3.Справочник разделов объяснительной записки",
            },
        ),
        migrations.AlterModelOptions(
            name="postgraduate",
            options={
                "ordering": ["id"],
                "verbose_name": "Аспирант",
                "verbose_name_plural": "1.Аспиранты",
            },
        ),
    ]
