# Generated by Django 4.1.1 on 2022-12-21 20:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explanatorynote",
            name="application_area",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
