# Generated by Django 4.1.1 on 2022-12-23 20:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0002_alter_dissertationtopic_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="explanatorynotesection",
            options={"ordering": ["sort"]},
        ),
        migrations.AlterField(
            model_name="dissertationtopic",
            name="name",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
