# Generated by Django 4.1.1 on 2022-12-21 20:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0002_alter_explanatorynote_application_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dissertationtopic",
            name="name",
            field=tinymce.models.HTMLField(),
        ),
    ]
