# Generated by Django 4.1.1 on 2022-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0003_alter_dissertationtopic_postgraduate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dissertationtopic",
            options={
                "ordering": ["id"],
                "verbose_name": "Тема диссертации",
                "verbose_name_plural": "Темы диссертации",
            },
        ),
        migrations.AlterModelOptions(
            name="postgraduate",
            options={
                "ordering": ["id"],
                "verbose_name": "Аспирант",
                "verbose_name_plural": "Аспиранты",
            },
        ),
        migrations.AlterField(
            model_name="dissertationtopic",
            name="protocol_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
