# Generated by Django 4.1.1 on 2022-11-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postgraduates", "0004_alter_dissertationtopic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explanatorynote",
            name="postgraduate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanatory_notes",
                to="postgraduates.postgraduate",
            ),
        ),
    ]
