# Generated by Django 4.1.1 on 2023-01-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('form_of_study', models.CharField(choices=[('NA', 'Не выбрано'), ('FT', 'Очное'), ('DL', 'Заочное')], default='NA', max_length=2)),
                ('number_of_years', models.SmallIntegerField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'новое'), (5, 'одобрено'), (10, 'отказано')], default=1)),
                ('is_terms_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculties.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявления',
                'verbose_name_plural': 'Список заявлений',
                'ordering': ['application_date', 'id'],
            },
        ),
    ]
