# Generated by Django 4.1.1 on 2023-01-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanatoryNoteSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sort', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Раздел объяснительной записки',
                'verbose_name_plural': '3.Справочник разделов объяснительной записки',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_study', models.CharField(choices=[('NA', 'Не выбрано'), ('FT', 'Очное'), ('DL', 'Заочное')], default='NA', max_length=2)),
                ('number_of_years', models.SmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.department')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.specialty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.supervisor')),
            ],
            options={
                'verbose_name': 'Аспирант',
                'verbose_name_plural': '1.Аспиранты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExplanatoryNoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('approval_status', models.IntegerField(choices=[(1, 'не проверено'), (3, 'доработка'), (5, 'утверждено')], default=1)),
                ('sort', models.IntegerField()),
                ('is_custom', models.BooleanField(default=False)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('postgraduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expl_note_sections', to='postgraduates.postgraduate')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_candidate_exam', models.BooleanField(default=False)),
                ('mark', models.IntegerField(choices=[(-1, 'не выставлено'), (0, 'зачет'), (2, 'неудовлетворительно'), (3, 'удовлетворительно'), (4, 'хорошо'), (5, 'отлично')], default=-1)),
                ('postgraduate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postgraduates.postgraduate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculties.subject')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DissertationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=250, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True)),
                ('postgraduate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='postgraduates.postgraduate')),
            ],
            options={
                'verbose_name': 'Тема диссертации',
                'verbose_name_plural': '2.Темы диссертации',
                'ordering': ['id'],
            },
        ),
    ]
